# Generated by Django 4.2.1 on 2023-06-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
