# Generated by Django 4.2.1 on 2023-06-02 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoDB', '0002_teacher_size_alter_teacher_age'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
    ]
